# Generated by Django 5.1.3 on 2024-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='todos', to='todo_app.tag'
            ),
        ),
    ]
